# Generated by Django 2.0.6 on 2020-06-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Flores',
        ),
    ]
