# Generated by Django 2.0.6 on 2020-06-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0003_auto_20200613_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flor',
            options={'ordering': ['nombre'], 'verbose_name': 'Flor', 'verbose_name_plural': 'Flores'},
        ),
    ]
